version: "3"

services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    environment:
      - SPARK_HOME=/opt/spark
      - PYSPARK_PYTON=/usr/bin/python3.9
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/spark/bin
    ports:
      - 8888:8888
      - 8080:8080
      - 18080:18080